### ISSUE TITLE
Failed to encrypt/descrypt

### ISSUE THREAD

**Issue by mzander** [snatik/android-storage#28]
Hi,

first of all thank you for the great library.

When I try to read a previously (crypted) stored text file I get those exception.
```
W/System.err: java.lang.RuntimeException: Failed to encrypt/descrypt
W/System.err:     at com.sromku.simple.storage.security.SecurityUtil.encrypt(SecurityUtil.java:79)
W/System.err:     at com.sromku.simple.storage.AbstractDiskStorage.encrypt(AbstractDiskStorage.java:411)
W/System.err:     at com.sromku.simple.storage.AbstractDiskStorage.readFile(AbstractDiskStorage.java:386)
W/System.err:     at com.sromku.simple.storage.AbstractDiskStorage.readFile(AbstractDiskStorage.java:161)
W/System.err:     at com.sromku.simple.storage.InternalStorage.readFile(InternalStorage.java:18)
W/System.err:     at com.sromku.simple.storage.AbstractDiskStorage.readTextFile(AbstractDiskStorage.java:169)
W/System.err:     at com.sromku.simple.storage.InternalStorage.readTextFile(InternalStorage.java:18)
```

which is caused by

```
W/System.err: Caused by: javax.crypto.BadPaddingException: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```

The keys are exactly the same as they were used for writing the file.

Thanks,
Moritz

**Comment by mzander** [comment]
I found that this is only the case when I am restarting the App and using the same keys for the stored file.

I am new to encryption but maybe this occurs because you are using always another random generated salt?

**Comment by sromku** [comment]
It's a bug and very bad thing to generate new random salt on every app session :( 
Fixed in latest version 🎉
