### ISSUE TITLE
Bug: Can't create file on ExternalStorage

### ISSUE THREAD

**Issue by stefanionescu** [snatik/android-storage#35]
java.lang.RuntimeException: Failed to create
                                                                             at 
    com.sromku.simple.storage.AbstractDiskStorage.createFile(AbstractDiskStorage.java:129)
                                                                             at 
    com.sromku.simple.storage.ExternalStorage.createFile(ExternalStorage.java:17)
                                                                             at 
    com.sromku.simple.storage.AbstractDiskStorage.createFile(AbstractDiskStorage.java:104)
                                                                             at 
    com.sromku.simple.storage.ExternalStorage.createFile(ExternalStorage.java:17)
                                                                             at 
    com.stefanionescu.propi.EditActivity.update_file(EditActivity.java:761)
                                                                             at 
    com.stefanionescu.propi.EditActivity.onClick(EditActivity.java:537)
                                                                             at android.view.View.performClick(View.java:5697)
                                                                             at android.view.View$PerformClick.run(View.java:22526)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                             at 
    android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at 
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                             at 
     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                          Caused by: java.io.FileNotFoundException: /storage/emulated/0/.secure/info.txt: open failed: ENOENT (No such file or directory)
                                                                             at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                             at 
    com.sromku.simple.storage.AbstractDiskStorage.createFile(AbstractDiskStorage.java:116)
                                                                             at 
    com.sromku.simple.storage.ExternalStorage.createFile(ExternalStorage.java:17) 
                                                                             at 
    com.sromku.simple.storage.AbstractDiskStorage.createFile(AbstractDiskStorage.java:104) 
                                                                             at 
    com.sromku.simple.storage.ExternalStorage.createFile(ExternalStorage.java:17) 
                                                                             at 
    com.stefanionescu.propi.EditActivity.update_file(EditActivity.java:761) 
                                                                             at 
     com.stefanionescu.propi.EditActivity.onClick(EditActivity.java:537) 
                                                                             at android.view.View.performClick(View.java:5697) 
                                                                             at android.view.View$PerformClick.run(View.java:22526) 
                                                                             at android.os.Handler.handleCallback(Handler.java:739) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:158) 
                                                                             at 
    android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at 
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                             at 
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                          Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                             at libcore.io.Posix.open(Native Method)
                                                                             at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                             at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                             at 
    com.sromku.simple.storage.AbstractDiskStorage.createFile(AbstractDiskStorage.java:116) 
                                                                             at 
    com.sromku.simple.storage.ExternalStorage.createFile(ExternalStorage.java:17) 
                                                                             at 
    com.sromku.simple.storage.AbstractDiskStorage.createFile(AbstractDiskStorage.java:104) 
                                                                             at 
    com.sromku.simple.storage.ExternalStorage.createFile(ExternalStorage.java:17) 
                                                                             at 
    com.stefanionescu.propi.EditActivity.update_file(EditActivity.java:761) 
                                                                             at 
    com.stefanionescu.propi.EditActivity.onClick(EditActivity.java:537) 
                                                                             at android.view.View.performClick(View.java:5697) 
                                                                             at android.view.View$PerformClick.run(View.java:22526) 
                                                                             at android.os.Handler.handleCallback(Handler.java:739) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:158) 
                                                                             at 
    android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at 
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                             at 
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

I can't create a text file in the external storage. Can you kindly help with this?

**Comment by stefanionescu** [comment]
Tested again. If I use Internal Storage, I can create a both files and directories. If I use External, I can only create directories.

The device that I use is Samsung Galaxy S5, Android 6.0

**Comment by sromku** [comment]
Sounds strange. From exception you got, it looks like `.secure` folder doesn't exist and thus you can't create the file inside. I just tested by creating folder `.secure` and file `info.txt` inside the folder on external storage and it worked for me. 

Please try latest version of this library. I have updated a lot, and you can also find a new sample app.
